// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_user_eventdetails from "./routes/api/user/eventdetails.ts";
import * as $api_user_search from "./routes/api/user/search.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $users_find_user from "./routes/users/find_user.tsx";
import * as $users_user from "./routes/users/user.tsx";
import * as $InputBlock_InputBlock from "./islands/InputBlock/InputBlock.tsx";
import * as $LogIn_LogIn from "./islands/LogIn/LogIn.tsx";
import * as $MenuButton_MenuButton from "./islands/MenuButton/MenuButton.tsx";
import * as $NavButton_NavButton from "./islands/NavButton/NavButton.tsx";
import * as $NavLogIn_NavLogSec from "./islands/NavLogIn/NavLogSec.tsx";
import * as $SearchPage_SearchPage from "./islands/SearchPage/SearchPage.tsx";
import * as $SideNav_NavBlock from "./islands/SideNav/NavBlock.tsx";
import * as $UserPage_UseName from "./islands/UserPage/UseName.tsx";
import * as $UserPage_User from "./islands/UserPage/User.tsx";
import * as $UserPage_UserPage from "./islands/UserPage/UserPage.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/user/eventdetails.ts": $api_user_eventdetails,
    "./routes/api/user/search.ts": $api_user_search,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/users/find_user.tsx": $users_find_user,
    "./routes/users/user.tsx": $users_user,
  },
  islands: {
    "./islands/InputBlock/InputBlock.tsx": $InputBlock_InputBlock,
    "./islands/LogIn/LogIn.tsx": $LogIn_LogIn,
    "./islands/MenuButton/MenuButton.tsx": $MenuButton_MenuButton,
    "./islands/NavButton/NavButton.tsx": $NavButton_NavButton,
    "./islands/NavLogIn/NavLogSec.tsx": $NavLogIn_NavLogSec,
    "./islands/SearchPage/SearchPage.tsx": $SearchPage_SearchPage,
    "./islands/SideNav/NavBlock.tsx": $SideNav_NavBlock,
    "./islands/UserPage/UseName.tsx": $UserPage_UseName,
    "./islands/UserPage/User.tsx": $UserPage_User,
    "./islands/UserPage/UserPage.tsx": $UserPage_UserPage,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
